spring.config.import=optional:file:.env[.properties]
logging.level.org.springframework.web=DEBUG
app.jwt.secret=${JWT_SECRET}
app.computer.password=${COMPUTER_PASSWORD}

server.servlet.session.cookie.same-site=strict
server.servlet.session.timeout=15m

websocket.csrf.enable=0

spring.datasource.url=jdbc:postgresql://192.168.1.18:5432/chesstopia
spring.datasource.username=chesstopia_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

app.allowed-origin=https://www.jacob-ferrell.com