spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/chesstopia}
spring.jpa.hibernate.ddl-auto=update
app.allowed-origin=${APP_ALLOWED_ORIGIN:https://www.jacob-ferrell.com}
